# This is a basic workflow to help you get started with Actions

name: DeployToAWS


# Controls when the workflow will run

on:

  # Triggers the workflow on push or pull request events but only for the main branch.

  push:

    branches: [ main ]

  # pull_request:

  #   branches: [ main ]



  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  deploy:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest



    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3



      # Runs a single command using the runners shell

      - name: Run a one-line script

        run: echo Hello, world!



      # Runs a set of commands using the runners shell

      - name: Run a multi-line script

        run: |

          echo Add other actions to build,

          echo test, and deploy your project.

      - name: Setup Packer

        # You may pin to the exact commit or the version.

        # uses: hashicorp-contrib/setup-packer@b9dd0b644cd73b8fe7ae5e96f6387015d25401ca

        uses: hashicorp-contrib/setup-packer@v1.0.0

     
          
      - name: Run packer commands

        run: |

          cd packer

          packer init .

          packer fmt .

          packer validate .

          packer build .

        env:

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}          

          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          AWS_REGION: "us-east-1"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_R }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_R }}
          AWS_REGION: "us-east-1"

      - name: AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.4
        with:
          version: 2
      - run: |
          aws --version
          aws ec2 create-launch-template-version --launch-template-name ass10-launch-template --source-version 1 --launch-template-data "ImageId=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)"
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name ass10-auto-Scaling-Group --launch-template LaunchTemplateName='ass10-launch-template',Version='$Latest'          
          aws autoscaling start-instance-refresh --auto-scaling-group-name ass10-auto-Scaling-Group
        shell: bash     